# Generated by Django 4.2.5 on 2023-09-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('diretor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('ano_lancamento', models.IntegerField()),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
